/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JButton;
import Controlador.*;
/**
 *
 * @author COSAS DE LA Y
 */
public class Meritos extends javax.swing.JFrame {

    /**
     * Creates new form Meritos
     */
    public Meritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        mensaje_2 = new javax.swing.JLabel();
        nombre_usuario = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        manesaje_5 = new javax.swing.JLabel();
        B_G_U2 = new javax.swing.JCheckBox();
        B_C2 = new javax.swing.JCheckBox();
        B_T2 = new javax.swing.JCheckBox();
        B_C_A1 = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        mensaje_3 = new javax.swing.JLabel();
        SI_BACHILLERATO2 = new javax.swing.JCheckBox();
        NO_BACHILLERATO2 = new javax.swing.JCheckBox();
        mensaje_5 = new javax.swing.JLabel();
        SI_BACHILLERATO3 = new javax.swing.JCheckBox();
        NO_BACHILLERATO3 = new javax.swing.JCheckBox();
        mensaje_6 = new javax.swing.JSeparator();
        mensaje_9 = new javax.swing.JLabel();
        mensaje_10 = new javax.swing.JLabel();
        medicina1 = new javax.swing.JCheckBox();
        enfermeria1 = new javax.swing.JCheckBox();
        fisioterapia1 = new javax.swing.JCheckBox();
        dietetica1 = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        mensaje_11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        auditoria1 = new javax.swing.JCheckBox();
        administracion2 = new javax.swing.JCheckBox();
        economia1 = new javax.swing.JCheckBox();
        finanzas1 = new javax.swing.JCheckBox();
        gastronomia1 = new javax.swing.JCheckBox();
        mensaje_12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        agropeciaria1 = new javax.swing.JCheckBox();
        alimentos = new javax.swing.JCheckBox();
        ambiental = new javax.swing.JCheckBox();
        industrial = new javax.swing.JCheckBox();
        ing_quimica = new javax.swing.JCheckBox();
        biologia3 = new javax.swing.JCheckBox();
        escenicas = new javax.swing.JCheckBox();
        mensaje_13 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        bio_farmacia1 = new javax.swing.JCheckBox();
        visuales = new javax.swing.JCheckBox();
        idiomas = new javax.swing.JCheckBox();
        psicopedadogia = new javax.swing.JCheckBox();
        psicologia1 = new javax.swing.JCheckBox();
        psicologia_clinica = new javax.swing.JCheckBox();
        mensaje_14 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        derecho = new javax.swing.JCheckBox();
        mensaje_15 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        geologia = new javax.swing.JCheckBox();
        computacion1 = new javax.swing.JCheckBox();
        arquitectura = new javax.swing.JCheckBox();
        telecomunicaciones1 = new javax.swing.JCheckBox();
        civil = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 578));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 66, 109));

        name.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Univesidad Tecnica Particular de Loja");

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXTRAS/LOGO MEJORADO.png"))); // NOI18N
        logo1.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1229, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, -1));

        jPanel3.setBackground(new java.awt.Color(0, 66, 109));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXTRAS/LOGO MEJORADO.png"))); // NOI18N
        logo.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(logo))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 390, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXTRAS/fondo2.0.1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 400, 640));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        mensaje_2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        mensaje_2.setText("Proceso de inscripcion ");

        nombre_usuario.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        nombre_usuario.setForeground(new java.awt.Color(153, 153, 153));
        nombre_usuario.setText("Ingrese su nombre y su apellido");
        nombre_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_usuarioMousePressed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        manesaje_5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        manesaje_5.setText("Que tipo debachillearto tiene usted? (Están con sus respectivas siglas)");

        B_G_U2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_G_U2.setText("B.G.U");
        B_G_U2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B_G_U2MousePressed(evt);
            }
        });

        B_C2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_C2.setText("B.C");
        B_C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B_C2MousePressed(evt);
            }
        });

        B_T2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_T2.setText("B.T");
        B_T2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B_T2MousePressed(evt);
            }
        });

        B_C_A1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_C_A1.setText("B.C.A");
        B_C_A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B_C_A1MousePressed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        mensaje_3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        mensaje_3.setText("Es usted abanderado de su colegio?");

        SI_BACHILLERATO2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        SI_BACHILLERATO2.setText("SI");

        NO_BACHILLERATO2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        NO_BACHILLERATO2.setText("NO");

        mensaje_5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        mensaje_5.setText("Usted posee una discapacidad mayor al 35%?");

        SI_BACHILLERATO3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        SI_BACHILLERATO3.setText("SI");

        NO_BACHILLERATO3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        NO_BACHILLERATO3.setText("NO");

        mensaje_6.setForeground(new java.awt.Color(0, 0, 0));

        mensaje_9.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        mensaje_9.setText("A que carrera desea ingreasar?");

        mensaje_10.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_10.setText("Facultad de ciencias economicas y empresariales");

        medicina1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        medicina1.setText("Medicina");

        enfermeria1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        enfermeria1.setText("Enfermeria");

        fisioterapia1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        fisioterapia1.setText("Fisioterapia");

        dietetica1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        dietetica1.setText("Nutricion y dietetica");

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        mensaje_11.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_11.setText("Facultad de ciencias de la salud");

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        auditoria1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        auditoria1.setText("Contabilidad y auditoria");

        administracion2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        administracion2.setText("Administracion de empresas");

        economia1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        economia1.setText("Economia");

        finanzas1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        finanzas1.setText("Finanzas");

        gastronomia1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        gastronomia1.setText("Gastronomia");

        mensaje_12.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_12.setText("Facultad de ciencias exactas y naturales");

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        agropeciaria1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        agropeciaria1.setText("Agropecuaria");

        alimentos.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        alimentos.setText("Alimentos");

        ambiental.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        ambiental.setText("Inguienieria ambiental");

        industrial.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        industrial.setText("Inguienieria Industrial");

        ing_quimica.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        ing_quimica.setText("Inguienieria quimica");

        biologia3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        biologia3.setText("Biologia");

        escenicas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        escenicas.setText("Artes escenicas");

        mensaje_13.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_13.setText("Facultad de ciencias sociales, eduaccion y humanidades");

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        bio_farmacia1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        bio_farmacia1.setText("Bioquimica y farmacia");

        visuales.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        visuales.setText("Artes visuales");

        idiomas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        idiomas.setText("Pedadofia de los idiomas nacionales y extranjeros");

        psicopedadogia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        psicopedadogia.setText("Psicopedadogia");

        psicologia1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        psicologia1.setText("Psicologia");

        psicologia_clinica.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        psicologia_clinica.setText("Psicologia clinica");

        mensaje_14.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_14.setText("Ciencias juridicas y politicas");

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));

        derecho.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        derecho.setText("Derecho");

        mensaje_15.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_15.setText("Inguienieria y arquitectura");

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));

        geologia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        geologia.setText("Geologia");

        computacion1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        computacion1.setText("Computacion");

        arquitectura.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        arquitectura.setText("Arquitectura");

        telecomunicaciones1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        telecomunicaciones1.setText("Telecomunicaciones");

        civil.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        civil.setText("Inguienieria civil");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(alimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agropeciaria1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addGap(481, 481, 481))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ing_quimica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bio_farmacia1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(biologia3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ambiental, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(industrial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manesaje_5)
                            .addComponent(mensaje_5)
                            .addComponent(mensaje_6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensaje_9)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensaje_3)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NO_BACHILLERATO2)
                            .addComponent(SI_BACHILLERATO2)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NO_BACHILLERATO3)
                            .addComponent(SI_BACHILLERATO3)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enfermeria1)
                            .addComponent(medicina1)
                            .addComponent(fisioterapia1)
                            .addComponent(dietetica1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_T2)
                            .addComponent(B_C_A1)
                            .addComponent(B_C2)
                            .addComponent(B_G_U2)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psicologia_clinica)
                            .addComponent(psicologia1)
                            .addComponent(psicopedadogia)
                            .addComponent(visuales, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escenicas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idiomas)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auditoria1)
                            .addComponent(administracion2)
                            .addComponent(economia1)
                            .addComponent(finanzas1)
                            .addComponent(gastronomia1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje_14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mensaje_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mensaje_11)
                                .addComponent(mensaje_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mensaje_13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator11)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mensaje_15, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(derecho))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(computacion1)
                            .addComponent(geologia)
                            .addComponent(arquitectura)
                            .addComponent(telecomunicaciones1)
                            .addComponent(civil)))
                    .addComponent(mensaje_2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(mensaje_2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manesaje_5)
                .addGap(18, 18, 18)
                .addComponent(B_G_U2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_C2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_T2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_C_A1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensaje_3)
                .addGap(18, 18, 18)
                .addComponent(SI_BACHILLERATO2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NO_BACHILLERATO2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_5)
                .addGap(18, 18, 18)
                .addComponent(SI_BACHILLERATO3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NO_BACHILLERATO3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje_6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensaje_9)
                .addGap(22, 22, 22)
                .addComponent(mensaje_11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enfermeria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fisioterapia1)
                .addGap(12, 12, 12)
                .addComponent(dietetica1)
                .addGap(18, 18, 18)
                .addComponent(mensaje_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administracion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(auditoria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(economia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finanzas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gastronomia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agropeciaria1)
                    .addComponent(alimentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biologia3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ambiental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(industrial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ing_quimica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bio_farmacia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escenicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visuales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idiomas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psicologia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psicopedadogia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psicologia_clinica)
                .addGap(18, 18, 18)
                .addComponent(mensaje_14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derecho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computacion1)
                .addGap(10, 10, 10)
                .addComponent(geologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telecomunicaciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arquitectura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(civil)
                .addGap(0, 169, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 960, 1600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1826, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_usuarioMousePressed
         if (nombre_usuario.getText().equals("Ingrese su nombre y su apellido")) {
            nombre_usuario.setText("");
            nombre_usuario.setForeground(Color.black);
         }
    }//GEN-LAST:event_nombre_usuarioMousePressed

    private void B_G_U2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_G_U2MousePressed
     Procesae_usuario.Procesar_postulante("B_G_U2", B_G_U2, B_G_U2, B_C2, B_T2, B_C_A1);
    }//GEN-LAST:event_B_G_U2MousePressed

    private void B_C2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_C2MousePressed
       Procesae_usuario.Procesar_postulante("B_C2", B_C2, B_G_U2, B_C2, B_T2, B_C_A1);
    }//GEN-LAST:event_B_C2MousePressed

    private void B_T2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_T2MousePressed
      Procesae_usuario.Procesar_postulante("B_T2", B_T2, B_G_U2, B_C2, B_T2, B_C_A1);
    }//GEN-LAST:event_B_T2MousePressed

    private void B_C_A1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_C_A1MousePressed
        Procesae_usuario.Procesar_postulante("B_C_A1", B_C_A1, B_G_U2, B_C2, B_T2, B_C_A1);
    }//GEN-LAST:event_B_C_A1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox B_C2;
    private javax.swing.JCheckBox B_C_A1;
    private javax.swing.JCheckBox B_G_U2;
    private javax.swing.JCheckBox B_T2;
    private javax.swing.JCheckBox NO_BACHILLERATO2;
    private javax.swing.JCheckBox NO_BACHILLERATO3;
    private javax.swing.JCheckBox SI_BACHILLERATO2;
    private javax.swing.JCheckBox SI_BACHILLERATO3;
    private javax.swing.JCheckBox administracion2;
    private javax.swing.JCheckBox agropeciaria1;
    private javax.swing.JCheckBox alimentos;
    private javax.swing.JCheckBox ambiental;
    private javax.swing.JCheckBox arquitectura;
    private javax.swing.JCheckBox auditoria1;
    private javax.swing.JCheckBox bio_farmacia1;
    private javax.swing.JCheckBox biologia3;
    private javax.swing.JCheckBox civil;
    private javax.swing.JCheckBox computacion1;
    private javax.swing.JCheckBox derecho;
    private javax.swing.JCheckBox dietetica1;
    private javax.swing.JCheckBox economia1;
    private javax.swing.JCheckBox enfermeria1;
    private javax.swing.JCheckBox escenicas;
    private javax.swing.JCheckBox finanzas1;
    private javax.swing.JCheckBox fisioterapia1;
    private javax.swing.JCheckBox gastronomia1;
    private javax.swing.JCheckBox geologia;
    private javax.swing.JCheckBox idiomas;
    private javax.swing.JCheckBox industrial;
    private javax.swing.JCheckBox ing_quimica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel manesaje_5;
    private javax.swing.JCheckBox medicina1;
    private javax.swing.JLabel mensaje_10;
    private javax.swing.JLabel mensaje_11;
    private javax.swing.JLabel mensaje_12;
    private javax.swing.JLabel mensaje_13;
    private javax.swing.JLabel mensaje_14;
    private javax.swing.JLabel mensaje_15;
    private javax.swing.JLabel mensaje_2;
    private javax.swing.JLabel mensaje_3;
    private javax.swing.JLabel mensaje_5;
    private javax.swing.JSeparator mensaje_6;
    private javax.swing.JLabel mensaje_9;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nombre_usuario;
    private javax.swing.JCheckBox psicologia1;
    private javax.swing.JCheckBox psicologia_clinica;
    private javax.swing.JCheckBox psicopedadogia;
    private javax.swing.JCheckBox telecomunicaciones1;
    private javax.swing.JCheckBox visuales;
    // End of variables declaration//GEN-END:variables
}
