/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author COSAS DE LA Y
 */
public class Meritos extends javax.swing.JFrame {

    /**
     * Creates new form Meritos
     */
    public Meritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        mensaje_01 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        manesaje_04 = new javax.swing.JLabel();
        B_G_U1 = new javax.swing.JCheckBox();
        B_C1 = new javax.swing.JCheckBox();
        B_T1 = new javax.swing.JCheckBox();
        B_C_A = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        mensaje_02 = new javax.swing.JLabel();
        SI_BACHILLERATO1 = new javax.swing.JCheckBox();
        NO_BACHILLERATO1 = new javax.swing.JCheckBox();
        mensaje_4 = new javax.swing.JLabel();
        SI_BACHILLERATO = new javax.swing.JCheckBox();
        NO_BACHILLERATO = new javax.swing.JCheckBox();
        mensaje_05 = new javax.swing.JSeparator();
        mensaje_03 = new javax.swing.JLabel();
        mensaje_06 = new javax.swing.JLabel();
        medicina = new javax.swing.JCheckBox();
        medicina1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 578));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 66, 109));

        name.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Univesidad Tecnica Particular de Loja");

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXTRAS/LOGO MEJORADO.png"))); // NOI18N
        logo1.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1229, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXTRAS/fondo2.0.1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 400, 730));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        mensaje_01.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        mensaje_01.setText("Proceso de inscripcion ");

        nombre.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setText("Ingrese su nombre y su apellido");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        manesaje_04.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        manesaje_04.setText("Que tipo debachillearto tiene usted? (Están con sus respectivas siglas)");

        B_G_U1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_G_U1.setText("B.G.U");

        B_C1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_C1.setText("B.C");

        B_T1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_T1.setText("B.T");

        B_C_A.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        B_C_A.setText("B.C.A");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        mensaje_02.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        mensaje_02.setText("Es usted abanderado de su colegio?");

        SI_BACHILLERATO1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        SI_BACHILLERATO1.setText("SI");

        NO_BACHILLERATO1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        NO_BACHILLERATO1.setText("NO");

        mensaje_4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        mensaje_4.setText("Usted posee una discapacidad mayor al 35%?");

        SI_BACHILLERATO.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        SI_BACHILLERATO.setText("SI");

        NO_BACHILLERATO.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        NO_BACHILLERATO.setText("NO");

        mensaje_05.setForeground(new java.awt.Color(0, 0, 0));

        mensaje_03.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        mensaje_03.setText("A que carrera desea ingreasar?");

        mensaje_06.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_06.setText("Facultad de ciencias de la salud");

        medicina.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        medicina.setText("Medicina");

        medicina1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        medicina1.setText("Medicina");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje_01, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manesaje_04)
                            .addComponent(mensaje_4)
                            .addComponent(mensaje_05, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensaje_03)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensaje_02)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_C1)
                            .addComponent(B_G_U1)
                            .addComponent(B_T1)
                            .addComponent(B_C_A)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NO_BACHILLERATO1)
                            .addComponent(SI_BACHILLERATO1)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NO_BACHILLERATO)
                            .addComponent(SI_BACHILLERATO)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(mensaje_06))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicina1)
                            .addComponent(medicina))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(mensaje_01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manesaje_04)
                .addGap(18, 18, 18)
                .addComponent(B_G_U1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_C1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_C_A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensaje_02)
                .addGap(18, 18, 18)
                .addComponent(SI_BACHILLERATO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NO_BACHILLERATO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SI_BACHILLERATO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NO_BACHILLERATO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje_05, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensaje_03)
                .addGap(18, 18, 18)
                .addComponent(mensaje_06)
                .addGap(18, 18, 18)
                .addComponent(medicina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicina1)
                .addGap(0, 255, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 670, 930));

        jPanel3.setBackground(new java.awt.Color(0, 66, 109));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXTRAS/LOGO MEJORADO.png"))); // NOI18N
        logo.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, 460, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox B_C1;
    private javax.swing.JCheckBox B_C_A;
    private javax.swing.JCheckBox B_G_U1;
    private javax.swing.JCheckBox B_T1;
    private javax.swing.JCheckBox NO_BACHILLERATO;
    private javax.swing.JCheckBox NO_BACHILLERATO1;
    private javax.swing.JCheckBox SI_BACHILLERATO;
    private javax.swing.JCheckBox SI_BACHILLERATO1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel manesaje_04;
    private javax.swing.JCheckBox medicina;
    private javax.swing.JCheckBox medicina1;
    private javax.swing.JLabel mensaje_01;
    private javax.swing.JLabel mensaje_02;
    private javax.swing.JLabel mensaje_03;
    private javax.swing.JSeparator mensaje_05;
    private javax.swing.JLabel mensaje_06;
    private javax.swing.JLabel mensaje_4;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
